name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'generateThemes/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'gradle.properties'
      - '**.gradle.kts'
  pull_request:
    paths:
      - 'src/**'
      - 'generateThemes/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'gradle.properties'
      - '**.gradle.kts'

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: 'gradle'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.1.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Node Dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Theme
        run: pnpm generate:themes

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: "Asteria Theme-Snapshot.jar"
          path: build/libs/*.jar

      - name: Output Unreleased Changes
        run: |
          echo "# 🚧 Unreleased 🚧" >> $GITHUB_STEP_SUMMARY
          echo "$(./gradlew getChangelog --unreleased --no-header --console=plain -q)" >> $GITHUB_STEP_SUMMARY
